<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNzpaigh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNzpaigh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNzpaigh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNzpaigh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNzpaigh\appProdProjectContainer([
    'container.build_hash' => 'Nzpaigh',
    'container.build_id' => '16515d01',
    'container.build_time' => 1660915527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNzpaigh');
